### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ihor-zinchenko** [oscartbeaumont-ext/electron-widevinecdm-dev#2]

**Comment by oscartbeaumont** [comment]
This package is an unmaintained playground. I recommended checking out my project ElectonPlayer as it contains a maintained version of this package. If you are developing for Linux don't use this package it is only for Mac (more details about how to use Widevine on both platforms can be found in my apps source code). This package also requires an older version of Electron to work correctly. Widevine support even in my app is currently not very good on Mac because the old browser version required for Widevine to work causes websites to not work (the issue tracker for my app will help to show you known not working websites). I am currently building a solution that is about a week from release that is similar to Electron and has a compatible API but is completely written from scratch and is designed to play DRM content (it doesn't use Widevine but in my research it is able to play all online streaming services). If you are interested I will link to the project here once it is released.
